
# shell = "nu"
[window]
opacity = 1.0

[colors.cursor]
cursor = "0x528BFF"
text = "0x282c34"

[colors.normal]
black = "0x282c34"
blue = "0x61AFEF"
cyan = "0x56B6C2"
green = "0x98C379"
magenta = "0xC678DD"
red = "0xE06C75"
white = "0xF0F0F0"
yellow = "0xE5C07B"

[colors.primary]
background = "0x282c34"
foreground = "0xf0f0f0"

[colors.selection]
background = "0x2C313C"
foreground = "0xf0f0f0"

[font]
size = 6.75

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3
